# Generated by Django 4.1.1 on 2022-09-20 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportss', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ('-created',)},
        ),
    ]
